// --- Disable static generation and force Node runtime ---
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const revalidate = 0;

import { NextResponse } from "next/server";

export async function GET(
  req: Request,
  { params }: { params: { id: string } }
) {
  // ✅ Lazy import Node-only modules so they are loaded only at runtime
  const { PrismaClient } = await import("@prisma/client");
  const PDFDocument = (await import("pdfkit")).default;

  const prisma = new PrismaClient();
  const auctionId = Number(params.id);

  if (!auctionId) {
    return NextResponse.json({ error: "Invalid auction ID" }, { status: 400 });
  }

  const auction = await prisma.auction.findUnique({
    where: { id: auctionId },
    include: { items: true, buyer: true },
  });

  if (!auction) {
    return NextResponse.json({ error: "Auction not found" }, { status: 404 });
  }

  const bids = await prisma.bid.findMany({
    where: { item: { auctionId } },
    include: { supplier: true, item: true },
    orderBy: { bidValue: "asc" },
  });

  // --- Generate PDF in memory ---
  const chunks: Buffer[] = [];
  const doc = new PDFDocument({ margin: 40, size: "A4" });

  doc.on("data", (chunk: Buffer) => chunks.push(chunk));
  const done = new Promise<Buffer>((resolve) =>
    doc.on("end", () => resolve(Buffer.concat(chunks)))
  );

  // Header
  doc.fontSize(18).text("Auction Summary Report", { align: "center" });
  doc.moveDown(0.5);
  doc
    .fontSize(12)
    .text(`Auction Title: ${auction.title}`)
    .text(`Buyer: ${auction.buyer?.username || "N/A"}`)
    .text(`Status: ${auction.status}`)
    .text(`Start Price: ${auction.startPrice}`)
    .moveDown(1);

  // Item summaries
  doc.fontSize(14).text("Item-wise Summary", { underline: true });
  doc.moveDown(0.5);

  for (const item of auction.items) {
    const itemBids = bids.filter((b) => b.itemId === item.id);
    const winner = itemBids.length > 0 ? itemBids[0] : null;

    doc.fontSize(12).text(`Item: ${item.description}`);
    doc.text(`Quantity: ${item.quantity} ${item.uom}`);
    if (winner) {
      doc.text(
        `Lowest Bid: ${winner.bidValue} by ${winner.supplier.username}`
      );
    } else {
      doc.text("No bids placed for this item yet.");
    }
    doc.moveDown(0.5);
  }

  // Footer
  doc.moveDown(1);
  doc
    .fontSize(10)
    .text("Generated by Reverse Auction Platform", { align: "center" });

  doc.end();
  const pdfBuffer = await done;

  // ✅ Convert Buffer → Uint8Array → Blob for web compatibility
  const uint8Array = new Uint8Array(pdfBuffer);
  const pdfBlob = new Blob([uint8Array], { type: "application/pdf" });

  // ✅ Return stream (safe BodyInit)
  return new NextResponse(pdfBlob.stream(), {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename="Auction_${auctionId}_Summary.pdf"`,
    },
  });
}
