import { NextRequest, NextResponse } from "next/server";
import { PrismaClient } from "@prisma/client";
import PDFDocument from "pdfkit";

const prisma = new PrismaClient();

export async function GET(
  req: NextRequest,
  { params }: { params: { id: string } }
) {
  const auctionId = Number(params.id);
  if (!auctionId) {
    return NextResponse.json({ error: "Invalid auction ID" }, { status: 400 });
  }

  const auction = await prisma.auction.findUnique({
    where: { id: auctionId },
    include: { items: true, buyer: true },
  });
  if (!auction) {
    return NextResponse.json({ error: "Auction not found" }, { status: 404 });
  }

  const bids = await prisma.bid.findMany({
    where: { item: { auctionId } },
    include: { supplier: true, item: true },
    orderBy: { bidValue: "asc" },
  });

  // ---- create a PDF stream ----
  const doc = new PDFDocument({ margin: 40, size: "A4" });

  // build the PDF
  doc.fontSize(18).text("Auction Summary Report", { align: "center" });
  doc.moveDown(0.5);
  doc
    .fontSize(12)
    .text(`Auction Title: ${auction.title}`)
    .text(`Buyer: ${auction.buyer?.username || "N/A"}`)
    .text(`Status: ${auction.status}`)
    .text(`Start Price: ${auction.startPrice}`)
    .moveDown(1);

  doc.fontSize(14).text("Item-wise Summary", { underline: true });
  doc.moveDown(0.5);

  for (const item of auction.items) {
    const itemBids = bids.filter((b) => b.itemId === item.id);
    const winner = itemBids.length > 0 ? itemBids[0] : null;

    doc.fontSize(12).text(`Item: ${item.description}`);
    doc.text(`Quantity: ${item.quantity} ${item.uom}`);
    if (winner) {
      doc.text(
        `Lowest Bid: ${winner.bidValue} by ${winner.supplier.username}`
      );
    } else {
      doc.text("No bids placed for this item yet.");
    }
    doc.moveDown(0.5);
  }

  doc.moveDown(1);
  doc
    .fontSize(10)
    .text("Generated by Reverse Auction Platform", { align: "center" });

  // close PDFKit stream and convert to Web ReadableStream
  const nodeStream = doc.pipe(require("stream").PassThrough());
  doc.end();

  const readable = new ReadableStream({
    start(controller) {
      nodeStream.on("data", (chunk: Buffer) => controller.enqueue(chunk));
      nodeStream.on("end", () => controller.close());
      nodeStream.on("error", (err: Error) => controller.error(err));
    },
  });

  return new NextResponse(readable, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": `attachment; filename=\"Auction_${auctionId}_Summary.pdf\"`,
    },
  });
}
